### ISSUE TITLE
Lock account while email authorizing 2fa process

### ISSUE THREAD

**Issue by mbassan** [wlox/wlox#19]
When a user receives an authorization email when activating 2fa, his account should be locked in the interim. This will prevent the user from forgetting.

**Comment by JULIETPAPA** [comment]
Thank you mbassan.  I couldn't agree more.  I signed on to github a little bit early prior to my needs.
And I have noticed as you that security is a good thing.  2FA seems to be the thing that works best in most situations and I am interested to see... will github adapt to the 2FA environment upon sign in or is the deal with India totally off of the table, because they apparently see a problem here.
