### ISSUE TITLE
update_v1.05.sql fails

### ISSUE THREAD

**Issue by ergofobe** [wlox/wlox#54]
On a fresh install of wlox.sql.gz, which has version 1.04, running update v1.05 fails with the following error:

ERROR 1060 (42S21) at line 8: Duplicate column name 'email_notify_fiat_withdrawals'

**Comment by Skarfurinn** [comment]
I had the same problem when trying to set up the exchange and in the end I just figured that this was already in the db (also because the last comment on the initial db is "DB update to 1.05") so I skipped this file. That however gave me a huge headache later on as there are 3 tables created at the end of this sql file. 

```
CREATE TABLE IF NOT EXISTS `site_users_access` (
  `site_user` int(10) unsigned NOT NULL,
  `start` bigint(20) unsigned NOT NULL,
  `last` bigint(20) unsigned NOT NULL,
  `attempts` int(10) unsigned NOT NULL,
  PRIMARY KEY (`site_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `site_users_catch` (
  `site_user` int(10) unsigned NOT NULL,
  `attempts` int(10) unsigned NOT NULL,
  PRIMARY KEY (`site_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ip_access_log` (
  `ip` bigint(20) NOT NULL,
  `timestamp` datetime NOT NULL,
  `login` enum('Y','N') NOT NULL DEFAULT 'N',
  KEY `ip` (`ip`),
  KEY `timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

UPDATE`status` SET `db_version` = '1.05' WHERE `status`.`id` =1;
```

If I were you I would just pick out the lines in the query that are generating the errors and try again. Repeat that till you get a successful import. As the errors that will be generated are all related to the fact that most of this is already in the db.

**Comment by mbassan** [comment]
I have created a new base DB file (wlox.sql.gz) that is at version 1.13, so those will no longer be necessary. Will try to find a better versioning mechanism in the near future.

**Comment by Skarfurinn** [comment]
Thanks for the update mbassan and keep up the good work. :thumbsup:

**Comment by mbassan** [comment]
Thank you!
